# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bmc', [dirname(__file__)])
        except ImportError:
            import _bmc
            return _bmc
        if fp is not None:
            try:
                _mod = imp.load_module('_bmc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _bmc = swig_import_helper()
    del swig_import_helper
else:
    import _bmc
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _bmc.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _bmc.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _bmc.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _bmc.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _bmc.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _bmc.SwigPyIterator_equal(self, x)

    def copy(self):
        return _bmc.SwigPyIterator_copy(self)

    def next(self):
        return _bmc.SwigPyIterator_next(self)

    def __next__(self):
        return _bmc.SwigPyIterator___next__(self)

    def previous(self):
        return _bmc.SwigPyIterator_previous(self)

    def advance(self, n):
        return _bmc.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _bmc.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _bmc.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _bmc.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _bmc.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _bmc.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _bmc.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _bmc.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _bmc.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _bmc.IntVector___nonzero__(self)

    def __bool__(self):
        return _bmc.IntVector___bool__(self)

    def __len__(self):
        return _bmc.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _bmc.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _bmc.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _bmc.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _bmc.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _bmc.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _bmc.IntVector___setitem__(self, *args)

    def pop(self):
        return _bmc.IntVector_pop(self)

    def append(self, x):
        return _bmc.IntVector_append(self, x)

    def empty(self):
        return _bmc.IntVector_empty(self)

    def size(self):
        return _bmc.IntVector_size(self)

    def swap(self, v):
        return _bmc.IntVector_swap(self, v)

    def begin(self):
        return _bmc.IntVector_begin(self)

    def end(self):
        return _bmc.IntVector_end(self)

    def rbegin(self):
        return _bmc.IntVector_rbegin(self)

    def rend(self):
        return _bmc.IntVector_rend(self)

    def clear(self):
        return _bmc.IntVector_clear(self)

    def get_allocator(self):
        return _bmc.IntVector_get_allocator(self)

    def pop_back(self):
        return _bmc.IntVector_pop_back(self)

    def erase(self, *args):
        return _bmc.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _bmc.new_IntVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _bmc.IntVector_push_back(self, x)

    def front(self):
        return _bmc.IntVector_front(self)

    def back(self):
        return _bmc.IntVector_back(self)

    def assign(self, n, x):
        return _bmc.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _bmc.IntVector_resize(self, *args)

    def insert(self, *args):
        return _bmc.IntVector_insert(self, *args)

    def reserve(self, n):
        return _bmc.IntVector_reserve(self, n)

    def capacity(self):
        return _bmc.IntVector_capacity(self)
    __swig_destroy__ = _bmc.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _bmc.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _bmc.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _bmc.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _bmc.DoubleVector___bool__(self)

    def __len__(self):
        return _bmc.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _bmc.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _bmc.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _bmc.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _bmc.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _bmc.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _bmc.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _bmc.DoubleVector_pop(self)

    def append(self, x):
        return _bmc.DoubleVector_append(self, x)

    def empty(self):
        return _bmc.DoubleVector_empty(self)

    def size(self):
        return _bmc.DoubleVector_size(self)

    def swap(self, v):
        return _bmc.DoubleVector_swap(self, v)

    def begin(self):
        return _bmc.DoubleVector_begin(self)

    def end(self):
        return _bmc.DoubleVector_end(self)

    def rbegin(self):
        return _bmc.DoubleVector_rbegin(self)

    def rend(self):
        return _bmc.DoubleVector_rend(self)

    def clear(self):
        return _bmc.DoubleVector_clear(self)

    def get_allocator(self):
        return _bmc.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _bmc.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _bmc.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _bmc.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _bmc.DoubleVector_push_back(self, x)

    def front(self):
        return _bmc.DoubleVector_front(self)

    def back(self):
        return _bmc.DoubleVector_back(self)

    def assign(self, n, x):
        return _bmc.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _bmc.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _bmc.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _bmc.DoubleVector_reserve(self, n)

    def capacity(self):
        return _bmc.DoubleVector_capacity(self)
    __swig_destroy__ = _bmc.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _bmc.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class BmcDm(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BmcDm, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BmcDm, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _bmc.new_BmcDm()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _bmc.delete_BmcDm
    __del__ = lambda self: None

    def open_dm(self, serial_number):
        return _bmc.BmcDm_open_dm(self, serial_number)

    def send_data(self, data):
        return _bmc.BmcDm_send_data(self, data)

    def send_data_custom_mapping(self, data, mapping):
        return _bmc.BmcDm_send_data_custom_mapping(self, data, mapping)

    def close_dm(self):
        return _bmc.BmcDm_close_dm(self)

    def default_mapping(self):
        return _bmc.BmcDm_default_mapping(self)

    def num_actuators(self):
        return _bmc.BmcDm_num_actuators(self)

    def get_status(self):
        return _bmc.BmcDm_get_status(self)

    def error_string(self, error_code):
        return _bmc.BmcDm_error_string(self, error_code)
BmcDm_swigregister = _bmc.BmcDm_swigregister
BmcDm_swigregister(BmcDm)

# This file is compatible with both classic and new-style classes.


